name: reVX
channels:
  - nrel
  - defaults
dependencies:
  - affine=2.3.0
  - attrs=21.2.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - blosc=1.21.0
  - bokeh=2.4.1
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.26
  - cached-property=1.5.2
  - cairo=1.16.0
  - certifi=2021.10.8
  - cfitsio=3.470
  - charls=2.2.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.0.0
  - curl=7.78.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.10.0
  - dask-core=2021.10.0
  - distributed=2021.10.0
  - expat=2.4.1
  - fiona=1.8.13.post1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - freexl=1.0.6
  - fsspec=2021.10.1
  - gdal=3.0.2
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geos=3.8.0
  - geotiff=1.6.0
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - h5py=3.6.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=58.2
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - jinja2=3.0.2
  - joblib=1.1.0
  - jpeg=9d
  - json-c=0.13.1
  - jxrlib=1.1
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libboost=1.73.0
  - libcurl=7.78.0
  - libcxx=12.0.0
  - libdap4=3.19.1
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgdal=3.0.2
  - libgfortran=3.0.1
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libpq=12.2
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - libzopfli=1.0.3
  - llvm-openmp=12.0.0
  - locket=0.2.1
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - more-itertools=8.12.0
  - msgpack-python=1.0.2
  - munch=2.5.0
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=2.6.3
  - nrel-pysam=2.2.0
  - nrel-pysam-stubs=2.2.0
  - nrel-rev=0.5.12
  - nrel-revx=0.3.39
  - nrel-rex=0.2.67
  - numexpr=2.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.4
  - partd=1.2.0
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.2.2
  - pixman=0.40.0
  - plotly=4.14.3
  - plotting=0.0.7
  - pluggy=0.13.1
  - poppler=0.81.0
  - poppler-data=0.4.10
  - postgresql=12.2
  - proj=6.2.1
  - psutil=5.8.0
  - psycopg2=2.8.6
  - py=1.10.0
  - pyparsing=3.0.4
  - pyproj=2.6.1.post1
  - pytest=6.2.4
  - python=3.7.11
  - python-dateutil=2.8.2
  - pytz=2021.3
  - pywavelets=1.1.1
  - pyyaml=6.0
  - rasterio=1.1.0
  - readline=8.1
  - retrying=1.3.3
  - rtree=0.9.7
  - scikit-image=0.18.3
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - seaborn=0.11.2
  - setuptools=58.0.4
  - shapely=1.7.1
  - six=1.16.0
  - snappy=1.1.8
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sqlite=3.36.0
  - tblib=1.7.0
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tiledb=2.2.9
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.2
  - tornado=6.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - wheel=0.37.0
  - xarray=0.19.0
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - zfp=0.5.5
  - zict=2.0.0
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - adal==1.2.7
    - cachetools==4.2.4
    - cffi==1.15.0
    - charset-normalizer==2.0.7
    - cryptography==35.0.0
    - future==0.18.2
    - global-land-mask==1.0.0
    - google-api-core==2.2.2
    - google-api-python-client==2.31.0
    - google-auth==1.35.0
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.4.6
    - googleapis-common-protos==1.53.0
    - h5pyd==0.9.0
    - hopp==0.0.5
    - httplib2==0.20.2
    - idna==3.3
    - isodate==0.6.0
    - msrest==0.6.21
    - msrestazure==0.6.4
    - oauthlib==3.1.1
    - protobuf==3.19.1
    - pvmismatch==4.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pyjwt==2.3.0
    - pysolar==0.10
    - python-dotenv==0.19.2
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - requests-unixsocket==0.2.0
    - rsa==4.7.2
    - timezonefinder==5.2.0
    - uritemplate==4.1.1
    - urllib3==1.26.7
