name: ExamplePipeline

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
        #include:
          #- os: ubuntu-latest
            #python-version: 3.7

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install conda dependencies
      shell: bash -l {0}
      run: |
        conda env update --file environment.yml --name base
    - uses: julia-actions/setup-julia@latest
      with:
        version: "1" # get the latest Julia version
    - name: Load dvc
      uses: iterative/setup-dvc@v1
    - name: Load dvc data
      shell: bash -l {0}
      run: |
        dvc update test/data -R
    - name: Run dvc pipeline
      shell: bash -l {0}
      run: |
        cd test
        dvc repro
